# Generated by Django 5.2 on 2025-10-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('images', models.ImageField(blank=True, upload_to='\\photos')),
            ],
        ),
    ]
