# Generated by Django 5.2 on 2025-11-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
