# Generated by Django 5.2 on 2025-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_items_options'),
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
